.prettierrc
- 설정 이후 추가 의견을 반영한 tabWidth 수정
```json
{
"plugins": ["prettier-plugin-tailwindcss"],
"tabWidth": 2,
"useTabs": false,
"singleQuote": false,
"trailingComma": "all",
"printWidth": 80,
"arrowParens": "always",
"bracketSpacing": true
}
```
- 작업 진행과 함께 다른 인원의 주장 및 불편함 제기 시, 추가 논의 후 다시 변경이 가능합니다.
2024.10.10
=> 🎨[Style] tabWidth 4에서 2로 수정 #2

src/app/(intro)/components/basicblock.tsx, src/app/admin/page.tsx
- 블록 최상단/최하단 이동 기능 구현
-
-
2024.10.12
=> ✨ [Feat] admin page 블록 이동 기능 구현 #14

next.config.js
=> 📦[Chore] next.config.js 중복 -> 삭제 #91

src/app/admin/layout.tsx, src/middleware.ts
- 오프라인 미팅 중 작업물 중간 병합, 점검
- 빌드 및 배포 테스트를 위한 최소한의 수정 후 dev 브랜치에 병합 진행 중
2024.10.20
=> ✨[Feat] 중간 병합 후 배포 테스트를 위한 커밋 #91

src/styles/global.css
- block layout - 제목 -> font bold 적용
- block layout - 뒤로가기 버튼 inline-block 으로
- 전체 영역 스크롤바 display none (global.css)
2024.10.22
=> ✨[Feat] block - layout 컴포넌트 css 수정 #94

.env, src/app/admin/block/image/components/image-box.tsx, src/app/admin/block/image/page.tsx, src/app/admin/block/video/page.tsx
- 이미지, 동영상 박스의 크기 조절 (width full)
- 이미지, 동영상 박스 테두리에 shadow 추가
- url 유효성 검사 수정 (입력된 문자열 삭제 시 동작하지 않던 문제 해결) 
2024.10.22
=> ✨[Feat] 이미지, 동영상 박스 css 변경, 각 url 유효성 검사 #88

src/app/admin/block/components/question-icon.tsx, tailwind.config.ts
- question-icon.tsx 아이콘 hover 영역 조정 
아이콘 영역에서만 hover 가 발생해야 하는데
hover 시 나오는 안내 문구의 div 에도 hover 발생하여 수정하였습니다.
2024.10.22
=> ✨[Feat] question-icon.tsx 아이콘 hover 영역 조정 #122

src/app/admin/(block)/divider/components/divider-selector.tsx
- 템플릿 리터럴 문자열 구문 수정 (백틱 추가)
- button 타입을 "button"으로 명시적 지정
- 타입 캐스팅 추가로 타입 안정성 개선
- e.preventDefault() 추가하여 의도치 않은 동작 방지
- 구분선 선택 시 정상적으로 선택
- 선택한 구분선이 상태에 제대로 반영
- 의도치 않은 커서 이동 현상 제거
2024.10.23
=> 🐛[Fix] 구분선 선택 기능 오작동 수정 #134

package-lock.json, package.json, src/app/admin/(block)/calendar/components/calendar-header.tsx, src/app/admin/(block)/calendar/components/calendar-view.tsx, src/app/admin/(block)/calendar/components/date-time-input.tsx, src/app/admin/(block)/calendar/components/list-view.tsx, src/app/admin/(block)/calendar/components/schedule-form.tsx, src/app/admin/(block)/calendar/components/schedule-list.tsx, src/app/admin/(block)/calendar/components/style-setting.tsx, src/app/admin/(block)/calendar/manage/page.tsx, src/app/admin/(block)/calendar/page.tsx
- 캘린더 블록에 공통 컴포넌트를 적용하여 페이지 구조 통일
- 전체적인 UI 및 레이아웃 수정, 리팩토링 진행
- 날짜/시간 선택 UI 개선 및 DatePicker 라이브러리 적용
- fetchCalendarBlock 호출 최적화
2024.10.28
=> 💄[Design] 캘린더 블록 UI 개선 #148

src/utils/apis/index.ts
- api 호출 메서드 사용 시 token 을 인자로 넘겨주도록 수정하였습니다
2024.10.30
=> 🐛[Fix] api utils #190

src/app/admin/(block)/block-menu.tsx, src/app/admin/(block)/components/buttons/add-button.tsx, src/app/admin/(block)/components/contour.tsx, src/app/admin/(block)/components/form-input.tsx, src/app/admin/(block)/components/question-icon.tsx, src/app/admin/(block)/components/text-input-box.tsx, src/app/admin/(block)/image/components/image-box.tsx, src/app/admin/(block)/video/page.tsx, src/styles/global.css, tailwind.config.ts
- 변수로 사용하던 조건부 스타일링 twMerge() 로 통일
- 색상 config 설정 색상으로 통일
2024.10.31
=> 💄[Design] 작업영역 style 단일화 (color 및 코드 스타일) #198

src/app/admin/(block)/image/page.tsx, src/lib/check-url.ts
- image url 확장자 검사 로직 제거
2024.10.31
=> 🐛[Fix] image url 확장자 검사 로직 제거 #200

src/app/admin/components/divide-block-sub/dot.tsx, src/app/admin/components/divide-block-sub/gap.tsx, src/app/admin/components/divide-block-sub/line.tsx, src/app/admin/components/divide-block-sub/point.tsx, src/app/admin/components/divide-block-sub/zigzag.tsx, src/app/admin/components/video-block.tsx
- basicblock하부컴포넌트(구분선) 이미지 적용
-
-
2024.10.31
=> ✨ [Feat] basicblock하부컴포넌트(구분선) 이미지 적용 #14

src/app/admin/(block)/calendar/components/schedule-form.tsx
- `getSequence` 호출 후 `nextSequence` 값 확인하여 타입 에러 방지
- `nextSequence`가 `undefined`일 경우 조기 리턴 추가
```tyepscript
const nextSequence = await getSequence(token);
if (!nextSequence) return;
requestBody = {
type: 7,
sequence: nextSequence + 1,
style: 1,
schedule: [newSchedule],
};
```
2024.10.31
=> 🐛[Fix] getSequence 타입 에러 방지 위한 기본값 설정 #206

src/app/admin/(block)/block-menu.tsx, src/app/admin/(block)/calendar/components/schedule-list.tsx, src/app/admin/(block)/calendar/page.tsx, src/app/admin/(block)/components/layout.tsx, src/app/admin/(block)/divider/page.tsx, src/app/admin/(block)/event/page.tsx, src/app/admin/(block)/image/page.tsx, src/app/admin/(block)/link/page.tsx, src/app/admin/(block)/text/page.tsx, src/app/admin/(block)/video/page.tsx, src/app/intro/page.tsx, src/app/join/components/animated-text.tsx, src/lib/check-url.ts
- useSearchParams() 사용 영역 Suspense 적용
- #211
```tsx
// src/app/admin/(block)/link/page.tsx
"use client";
import { useSearchParams } from "next/navigation";
import { useState, useEffect } from "react";
import { Suspense } from "react";
function LinkPage() {
const searchParams = useSearchParams();
const [paramValue, setParamValue] = useState<string | null>(null);
useEffect(() => {
const value = searchParams.get("param");
setParamValue(value);
}, [searchParams]);
return <div>Parameter Value: {paramValue}</div>;
}
export default function PageWithSuspense() {
return (
<Suspense fallback={<div>Loading...</div>}>
<LinkPage />
</Suspense>
);
}
```
2024.10.31
=> 🐛[Fix] useSearchParams() 사용 영역 Suspense 적용 #211

src/app/admin/(block)/block-menu.tsx, src/app/admin/components/preview/components/preview-video.tsx, src/app/admin/page.tsx, src/app/page.tsx
- main 페이지, admin - 미리보기 ui 스타일 디테일 #221 
2024.11.07
=> ✨[Feat] main 페이지, admin - 미리보기 ui 스타일 디테일 #221

src/app/profile/detail/page.tsx, src/app/profile/edit/page.tsx
-  profile/detail,profile/edit api 호출부 수정 #214
-
-
2024.mm.dd
=> ♻️ [Refactor] profile/detail,profile/edit api 호출부 수정 #214

src/app/admin/(block)/link/components/style-preview.tsx, src/app/admin/components/preview/components/preview-link.tsx, src/app/admin/components/preview/components/preview.tsx, src/app/admin/components/profile-box.tsx, src/app/admin/page.tsx, src/app/components/page/block-list.tsx, src/app/profile/detail/page.tsx, src/app/profile/edit/page.tsx
- block list 없을 때 조건부 렌더링 처리
- 메인페이지 링크 블록 타입 적용
2024.mm.dd
=> ✨[Feat] block list 없을 때 조건부 렌더링 처리, 메인페이지 링크 블록 타입 적용 #227

package-lock.json, package.json, src/app/admin/(block)/calendar/components/schedule-list.tsx, src/app/admin/(block)/calendar/components/style-setting.tsx, src/app/admin/(block)/paint/page.tsx, src/app/admin/components/preview/preview-modal.tsx, src/app/admin/page.tsx, src/utils/apis/index.ts
- admin 페이지 ui 깨지던 것을 수정하였습니다.
2024.11.10
=>  💄[Design]  admin 페이지 ui 수정 #232

src/app/admin/components/home-menu.tsx, src/app/api/protected/route.tsx, src/app/intro/components/UI/empty-block.tsx
- homemenu 수정
- protected api 작성
-
2024.11.10
=> ♻️ [Refactor] homemenu 수정, protected api 작성 #214

.github/workflows/deploy.yaml
=> 🐛[Fix] 백엔드 api 1차 구축 후 배포 시도 실패, 수정 #214

src/app/admin/(block)/link/components/link-form.tsx, src/app/admin/components/preview/components/preview-image.tsx, src/app/admin/components/preview/components/preview-link.tsx, src/app/admin/components/profile-box.tsx, src/app/api/link/add/route.tsx, src/app/layout.tsx, src/components/common/ui/theme-toggle.tsx, src/components/providers/theme-provider.tsx
- 기존 context api 사용하던 코드를 ThemeToggle 내에서 처리하도록 변경하였습니다.
개선은 되었으나 아직 시스템 설정 먼저 깜빡이는 경우가 발생하여 수정이 필요한 코드입니다.
2024.11.18
=> 🐛[Fix] 다크모드 적용 이슈 #252

src/app/api/link/list/update/route.tsx, src/app/api/user/add/route.tsx
- link list update api 구현
-
-
2024.11.21
=> [Feat] link list update api 구현

src/app/admin/page.tsx, src/app/components/circle-button-box.tsx, src/utils/apis/index.ts
- 캘린더 블록 순서 변경 api 추가
2024.11.21
=> ✨[Feat] 캘린더 블록 순서 변경 api 추가 #258

src/app/layout.tsx, src/app/page.tsx, src/components/common/ui/theme-toggle.tsx
- 다크모드 깜빡임 이슈 해결
cookie 를 이용하여 해결하였습니다.
사용자가 페이지 첫 진입 시 시스템 설정을 사용,
시스템 설정 값을 cookie 에 저장합니다.
이후에는 cookie 에 저장된 theme 값을 사용,
toggle 버튼 클릭 시 cookie 의 theme 을 변경하는 것으로 수정하였습니다.
2024.11.21
=> 🐛[Fix] 다크모드 깜빡임 이슈 #252

src/app/admin/(block)/block-menu.tsx, src/app/admin/components/block-list-section.tsx, src/app/admin/components/profile-box.tsx, src/app/components/page/block-list.tsx, src/types/block_types.ts, src/utils/apis/index.ts
- 블록 미리보기 모달 이슈 
- 캘린더 블록 접근 로직 
- zod 적용
2024.11.25
=> [Feat] 블록 미리보기 모달 이슈, 캘린더 블록 접근 로직, zod 적용

src/app/admin/components/block-list-section.tsx, src/app/admin/components/preview/components/preview-calendar.tsx, src/app/admin/components/preview/components/preview-divider.tsx, src/app/admin/components/preview/components/preview-event.tsx, src/app/admin/components/preview/components/preview-image.tsx, src/app/admin/components/preview/components/preview-link.tsx, src/app/admin/components/preview/components/preview-text.tsx, src/app/admin/components/preview/components/preview-video.tsx, src/app/admin/components/preview/preview-modal.tsx, src/app/layout.tsx
- 디자인, 레이아웃, 스타일 관련 작업 방법 및 방향성 수정을 위한 이슈와 브랜치 정리 예정
- 이 과정에서 develop 브랜치 병합 과정에서의 에러들 수정 내용 포함하여 pr 작성
2024.11.25
=> 🐛[Fix] 이슈, 브랜치 정리 전, 병합 에러 해결 #216

src/app/api/link/calendar/add/route.tsx
- calendar api  일부 구현
-
-
2024.11.25
=> ✨ [Feat] calendar api  일부 구현 #214

package-lock.json, package.json, src/app/admin/(block)/calendar/components/schedule-form.tsx, src/app/admin/(block)/calendar/components/schedule-list.tsx, src/app/admin/components/preview/preview-modal.tsx, src/app/admin/page.tsx, src/app/profile/edit/page.tsx, src/components/common/ui/theme-toggle.tsx, src/components/providers/theme-provider.tsx, src/config/types.tsx, src/types/apis.ts, src/types/block_types.ts, src/types/theme.ts, src/types/user.ts, src/utils/apis/index.ts
- 스케줄 추가 api 로직 변경 
-
-
2024.11.25
=> ✨[Feat] 스케줄 추가 api 로직 변경 #273

src/app/admin/(block)/components/form-input.tsx, src/app/intro/page.tsx, src/app/join/page.tsx, src/app/login/page.tsx, src/app/profile/detail/page.tsx, src/app/profile/edit/page.tsx, src/components/providers/theme-provider.tsx, src/styles/global.css
- 인트로, 로그인, 회원가입, 회원정보 수정 / 조회 페이지 반응형 적용
- FormInput 컴포넌트 수정
- 자동완성 입력값 존재 시, input 영역 스타일 조정
- 테마 전환 시의 애니메이션 조정
- theme-provider의 더 이상 사용하지 않는 코드 제거
2024.11.25
=> 💄[Design] 인트로, 로그인, 회원가입, 회원정보 조회 / 수정 페이지 레이아웃 완성 #270

src/app/admin/(block)/calendar/components/schedule-list.tsx, src/app/api/link/list/[id]/route.tsx
노지훈
- 동적 api  일부 구현
-
-
2024.11.26
=> ✨ [Feat] 동적 api  일부 구현 #214

src/app/api/link/calendar/update/route.tsx, src/app/api/link/update/route.tsx
노지훈
- calendar api 마무리
-
-
2024.11.26
=> [Feat] calendar api 마무리

src/app/api/login/route.tsx
노지훈
-   login api 수정
-
-
2024.11.26
=> [Feat] login api 수정

src/app/admin/(block)/components/contour.tsx, src/app/admin/(block)/link/components/style-preview.tsx, src/app/admin/components/admin-menu.tsx, src/app/admin/components/buttons/circle-button.tsx, src/app/admin/components/home-menu.tsx, src/app/admin/components/preview/components/preview-divider.tsx, src/app/admin/components/preview/components/preview-event.tsx, src/app/admin/components/preview/components/preview-image.tsx, src/app/admin/components/preview/components/preview-link.tsx, src/app/admin/components/preview/components/preview-text.tsx, src/app/admin/components/preview/components/preview-video.tsx, src/app/admin/components/preview/components/preview.tsx, src/app/admin/components/profile-box.tsx, src/app/admin/page.tsx, src/app/components/page/block-list.tsx, src/app/profile/[userId]/page.tsx, src/components/common/ui/theme-toggle.tsx
- 메인 페이지(src/app/profile/[userId]/page.tsx) 에 대한 전반적인 디자인(레이아웃) 조정 작업
- 반응형 디자인 적용을 위한 연결된 다수의 컴포넌트 조정
- 다크모드 완성을 위한 색상 및 레이아웃 다수 조정
- 통일성을 위한 스타일 코드 변경
- 작업 과정 중, 발견한 미사용 변수 및 주석 일부 정리
- 페이지에 다수의 컴포넌트가 불규칙적으로 묶여 있으므로, 다크모드 및 스타일(레이아웃) 완성을 위해선 추가 작업 필요.
2024.11.26
=> 💄[Design] 메인 페이지 디자인(레이아웃) 조정 중간 병합 #281

src/app/api/user/userlist/route.tsx
노지훈
-userlist api 구현
-
-
2024.11.27
=> [Feat] userlist api 구현
